version: "{build}"

image: Visual Studio 2017

configuration: Release

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

before_build:
  - dotnet restore

skip_tags: true

after_build:
  - for %%x in (win-x64 win-x86 win-arm win-arm64 linux-x64 linux-arm osx-x64) do (dotnet publish Aem -c Release -o %APPVEYOR_BUILD_FOLDER%\published-%%x --self-contained -r %%x)
  - for %%x in (win-x64 win-x86 win-arm win-arm64 linux-x64 linux-arm osx-x64) do (7z a Aem-%%x-v%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\published-%%x\*)

artifacts:
  - path: Aem-*-v%APPVEYOR_BUILD_VERSION%.zip

deploy:
  release: Aem-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: Fu6p8pFA2CEmOLfszUJf3ayF3dL9DsorBluoiQKJUNkpCcAlxlubScpvGDgxFAyH
  on:
    branch: master
